#!/bin/bash
xset +dpms
xset s off

if [ ! -f /etc/default/scrypi ]; then
  echo "$CONFIG not found" >&2
  exit 1
fi 
source /etc/default/scrypi

if [ -z $SCRY_DIR ]; then
  echo "SCRY_DIR not defined" >&2
  exit 1
fi

cd $SCRY_DIR && \
pm2 start ./config.json

START_URL=$HTTP_ORIGIN/

# Wait until http server is ready
while ! curl -s -o /dev/null $START_URL; do
  sleep 20
done

# Start the display manager
exec matchbox-window-manager -use_titlebar no &
# 
while true; do
  # Sometimes uzbl gets killed due to memory issues, this loop makes sure
  # it starts back up
  uzbl -u $START_URL -c $SCRY_DIR/config/uzbl.conf
done

